/**
 * FRAUDNEXUS AI — Investigation manager: creates investigation records on the world store,
 * runs the agent pipeline and applies human-in-the-loop decisions.
 * ⚠️ DEMO SIMULATION — synthetic data only.
 */
import { getWorld, nextAlert } from "./data/store";
import { runPipeline } from "./agents/pipeline";
import { txStatusFor } from "./risk";
import type { Investigation } from "./agents/types";
import type { Tx } from "./data/transactions";

export interface InvestigationRecord extends Investigation {
  seq: number;
}

const STATUS_LABELS: Record<Investigation["status"], string> = {
  running: "INVESTIGATION RUNNING",
  open: "OPEN — HUMAN REVIEW RECOMMENDED",
  escalated: "ESCALATED TO HUMAN FRAUD TEAM",
  safe: "RESOLVED — MARKED SAFE BY ANALYST",
  more_evidence: "MORE EVIDENCE REQUESTED BY ANALYST",
};

let nextInvSeq = 1;

/** Create (or fetch) the investigation for a transaction and run the full agent pipeline synchronously. */
export function startInvestigation(txnId: string, baseUrl = ""): InvestigationRecord | null {
  const world = getWorld();
  const existing = world.investigations?.get(txnId);
  if (existing) return existing;

  const tx = world.txns.get(txnId);
  if (!tx) return null;
  const record = world.customers.get(tx.customerId);
  if (!record) return null;

  const seq = nextInvSeq++;
  const year = new Date().getFullYear();
  const investigationId = `INV-${year}-${String(seq).padStart(3, "0")}`;

  const out = runPipeline({ customer: record.seed, txn: tx, history: record.history }, investigationId);

  const inv: InvestigationRecord = {
    seq,
    investigationId,
    txnId: tx.txnId,
    customerId: record.seed.customerId,
    customerName: record.seed.name,
    accountId: record.seed.accountId,
    status: out.riskAssessment.recommendation === "human_review" ? "open" : "running",
    statusLabel: out.riskAssessment.recommendation === "human_review" ? STATUS_LABELS.open : STATUS_LABELS.running,
    createdAt: new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }),
    riskScore: out.riskAssessment.score,
    riskLevel: out.riskAssessment.level,
    steps: out.steps,
    anomalies: out.anomalies,
    patterns: out.patterns,
    evidence: out.evidence,
    timeline: out.timeline,
    riskAssessment: out.riskAssessment,
    report: out.report,
    humanReview: {
      aiRecommendation:
        out.riskAssessment.recommendation === "human_review"
          ? "HIGH-RISK SUSPICIOUS ACTIVITY DETECTED. HUMAN REVIEW RECOMMENDED."
          : out.riskAssessment.recommendationText,
    },
    relatedEntities: out.relatedEntities,
  };

  world.investigations = world.investigations || new Map();
  world.investigations.set(txnId, inv);
  // Sync the final explainable score back onto the transaction so all tables stay consistent
  tx.riskScore = out.riskAssessment.score;
  tx.riskLevel = out.riskAssessment.level;
  tx.statusClass = txStatusFor(out.riskAssessment.score);
  world.version++;

  // Alerts generated by the investigation run
  nextAlert(world, {
    type: "INVESTIGATION STARTED",
    title: `Investigation ${investigationId} started`,
    message: `Seven-agent pipeline launched on ${tx.txnId} (${record.seed.name}).`,
    severity: "medium",
    timestamp: inv.createdAt,
    txnId: tx.txnId,
    customerId: inv.customerId,
    investigationId,
  });
  nextAlert(world, {
    type: "HUMAN REVIEW REQUIRED",
    title: `Human review required — ${tx.txnId}`,
    message: `Risk ${out.riskAssessment.score}/100 (${out.riskAssessment.label}). ${out.riskAssessment.recommendationText}`,
    severity: "high",
    timestamp: inv.createdAt,
    txnId: tx.txnId,
    customerId: inv.customerId,
    investigationId,
  });
  nextAlert(world, {
    type: "INVESTIGATION REPORT GENERATED",
    title: `Report generated for ${investigationId}`,
    message: `Structured investigation report with ${out.evidence.length} evidence items is ready for review.`,
    severity: "medium",
    timestamp: inv.createdAt,
    txnId: tx.txnId,
    customerId: inv.customerId,
    investigationId,
  });

  return inv;
}

export function getInvestigation(txnId: string): InvestigationRecord | undefined {
  return getWorld().investigations?.get(txnId);
}

export function listInvestigations(): InvestigationRecord[] {
  const invs = [...(getWorld().investigations?.values() ?? [])];
  return invs.sort((a, b) => b.seq - a.seq);
}

/** Human-in-the-loop action on a case. Returns updated record. */
export function applyHumanAction(
  txnId: string,
  action: "escalate" | "more_evidence" | "safe",
  reviewerNote?: string
): InvestigationRecord | null {
  const inv = getInvestigation(txnId);
  if (!inv) return null;
  const world = getWorld();
  const newStatus: Investigation["status"] = action === "escalate" ? "escalated" : action;
  inv.status = newStatus;
  inv.statusLabel = STATUS_LABELS[newStatus];
  inv.humanReview = {
    ...inv.humanReview!,
    action,
    actionAt: new Date().toLocaleString("en-IN", { dateStyle: "medium", timeStyle: "short" }),
    reviewerNote,
  };
  const actions: Record<string, string> = {
    escalate: "ESCALATED",
    more_evidence: "EVIDENCE REQUESTED",
    safe: "RESOLVED SAFE",
  };
  nextAlert(world, {
    type: "CASE UPDATED",
    title: `${inv.investigationId} ${actions[action]}`,
    message: `Case on ${inv.txnId} (${inv.customerName}) ${action === "safe" ? "was marked SAFE by the reviewing analyst" : action === "escalate" ? "was escalated to the human fraud team" : "awaited further evidence; analyst requested additional data"}.`,
    severity: action === "safe" ? "low" : "high",
    timestamp: inv.humanReview.actionAt!,
    txnId: inv.txnId,
    customerId: inv.customerId,
    investigationId: inv.investigationId,
  });
  world.version++;
  return inv;
}

/** Iterate all suspicious txns with agent findings (used by dashboard live feed). */
export function suspiciousTxns(): Tx[] {
  return getWorld().suspiciousTxns;
}
